services:
  database:
    image: mysql:8
    container_name: sicontrola_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sicontrola
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sicontrola_api
    environment:
      - DATABASE_URL=mysql://root:root@database:3306/sicontrola
      - BETTER_AUTH_SECRET=super_secret_key_123
      - BETTER_AUTH_URL=http://localhost:4000
    ports:
      - "4000:4000"
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sicontrola_web
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - BETTER_AUTH_URL=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data:
