services:

  database:
    image: mysql:8
    container_name: sicontrola_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sicontrola
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sicontrola_api
    environment:
      - DATABASE_URL=mysql://root:root@database:3306/sicontrola
      - BETTER_AUTH_SECRET=super_secret_key_123
      - BETTER_AUTH_URL=https://sicontrola.lofivora.space
    ports:
      - "7000:4000"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sicontrola_web
    environment:
      - NEXT_PUBLIC_API_URL=https://sicontrola.lofivora.space
      - BETTER_AUTH_URL=https://sicontrola.lofivora.space
    ports:
      - "7001:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
