import type {
  Student,
  Driver,
  BoardingRecord,
  Notification,
  Route,
  School,
  PlanConfig,
  DashboardStats,
  ChartData,
  User,
} from './types'

// ── Plan configurations ──
export const planConfigs: PlanConfig[] = [
  {
    plan: '1x',
    label: '1x por semana',
    price: 45.0,
    weeklyLimit: 1,
    description: 'Uma viagem por semana - ideal para quem tem aulas presenciais únicas',
  },
  {
    plan: '3x',
    label: '3x por semana',
    price: 95.0,
    weeklyLimit: 3,
    description: 'Três viagens por semana - mais flexibilidade para rotina de estudos',
  },
  {
    plan: '5x',
    label: '5x por semana',
    price: 150.0,
    weeklyLimit: 5,
    description: 'Cinco viagens por semana - frequência integral para dedicados',
  },
]

// ── Schools ──
export const schools: School[] = [
  {
    id: 'sch-001',
    name: 'Escola Municipal Professor Antônio Carlos',
    address: 'Rua das Flores, 123 - Centro',
  },
  {
    id: 'sch-002',
    name: 'Colégio Estadual Maria da Conceição',
    address: 'Avenida Brasil, 456 - Jardim América',
  },
  {
    id: 'sch-003',
    name: 'Instituto Federal de Educação - Campus Sul',
    address: 'Rodovia BR-101, Km 5 - Zona Sul',
  },
  {
    id: 'sch-004',
    name: 'Escola Técnica Senai Hermenegildo Campos de Almeida',
    address: 'Rua do Comércio, 789 - Distrito Industrial',
  },
  {
    id: 'sch-005',
    name: 'Centro Educacional Nossa Senhora Aparecida',
    address: 'Praça da Matriz, s/n - Centro',
  },
]

// ── Routes ──
export const routes: Route[] = [
  {
    id: 'route-001',
    name: 'Linha 01 - Centro → Bairro Novo',
    description: 'Saída do Terminal Central com destino ao Bairro Novo passando pelo Hospital Municipal',
  },
  {
    id: 'route-002',
    name: 'Linha 02 - Zona Sul → IFET',
    description: 'Rota da Zona Sul até o campus do Instituto Federal com parada no comércio local',
  },
  {
    id: 'route-003',
    name: 'Linha 03 - Jardim América → Centro',
    description: 'Do bairro Jardim América ao Centro, passando por 3 escolas no trajeto',
  },
  {
    id: 'route-004',
    name: 'Linha 04 - Distrito Industrial → Escola Técnica',
    description: 'Rota expressa do Distrito Industrial até o Senai, com parada no terminal de ônibus',
  },
  {
    id: 'route-005',
    name: 'Linha 05 - Vila Santa Cruz → Centro',
    description: 'Da Vila Santa Cruz ao Centro, com parada na Praça da Matriz',
  },
]

// ── Drivers ──
export const drivers: Driver[] = [
  { id: 'drv-001', name: 'Carlos Eduardo Silva', route: 'route-001' },
  { id: 'drv-002', name: 'Roberto Almeida Santos', route: 'route-002' },
  { id: 'drv-003', name: 'José Ferreira Lima', route: 'route-003' },
  { id: 'drv-004', name: 'Marcos Antônio Pereira', route: 'route-004' },
  { id: 'drv-005', name: 'Fernando Costa Oliveira', route: 'route-005' },
]

// ── Students (15+ with varied statuses) ──
export const students: Student[] = [
  {
    id: 'stu-001',
    name: 'Ana Clara Rodrigues',
    cpf: '12345678901',
    birthDate: '2005-03-15',
    phone: '31999887766',
    email: 'ana.clara@email.com',
    address: 'Rua das Palmeiras, 45 - Bairro Novo',
    neighborhood: 'Bairro Novo',
    institution: 'sch-001',
    course: 'Ensino Médio - 2º Ano',
    shift: 'morning',
    schoolYear: 2025,
    plan: '5x',
    planPrice: 150.0,
    status: 'approved',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-10T08:30:00Z',
    updatedAt: '2025-01-15T14:00:00Z',
    paymentStatus: 'paid',
    paymentDueDate: '2025-02-10',
    cardId: 'CARD-2025-0001',
    weeklyUsage: 3,
  },
  {
    id: 'stu-002',
    name: 'Pedro Henrique Souza',
    cpf: '23456789012',
    birthDate: '2006-07-22',
    phone: '31988776655',
    email: 'pedro.h@email.com',
    address: 'Rua dos Ipês, 120 - Jardim América',
    neighborhood: 'Jardim América',
    institution: 'sch-002',
    course: 'Ensino Médio - 1º Ano',
    shift: 'afternoon',
    schoolYear: 2025,
    plan: '3x',
    planPrice: 95.0,
    status: 'approved',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-12T10:00:00Z',
    updatedAt: '2025-01-18T16:30:00Z',
    paymentStatus: 'paid',
    paymentDueDate: '2025-02-12',
    cardId: 'CARD-2025-0002',
    weeklyUsage: 2,
  },
  {
    id: 'stu-003',
    name: 'Maria Eduarda Santos',
    cpf: '34567890123',
    birthDate: '2004-11-05',
    phone: '31977665544',
    email: 'maria.edu@email.com',
    address: 'Avenida Brasil, 320 - Zona Sul',
    neighborhood: 'Zona Sul',
    institution: 'sch-003',
    course: 'Técnico em Informática',
    shift: 'morning',
    schoolYear: 2025,
    plan: '5x',
    planPrice: 150.0,
    status: 'approved',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-08T09:15:00Z',
    updatedAt: '2025-01-14T11:00:00Z',
    paymentStatus: 'paid',
    paymentDueDate: '2025-02-08',
    cardId: 'CARD-2025-0003',
    weeklyUsage: 5,
  },
  {
    id: 'stu-004',
    name: 'Lucas Gabriel Oliveira',
    cpf: '45678901234',
    birthDate: '2005-01-30',
    phone: '31966554433',
    email: 'lucas.g@email.com',
    address: 'Rua do Comércio, 88 - Distrito Industrial',
    neighborhood: 'Distrito Industrial',
    institution: 'sch-004',
    course: 'Mecânica Industrial',
    shift: 'afternoon',
    schoolYear: 2025,
    plan: '3x',
    planPrice: 95.0,
    status: 'pending',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'pending',
    },
    createdAt: '2025-01-20T14:00:00Z',
    updatedAt: '2025-01-20T14:00:00Z',
    paymentStatus: 'pending',
    paymentDueDate: '2025-02-20',
    weeklyUsage: 0,
  },
  {
    id: 'stu-005',
    name: 'Isabella Ferreira Costa',
    cpf: '56789012345',
    birthDate: '2006-05-18',
    phone: '31955443322',
    email: 'isabella.f@email.com',
    address: 'Praça da Matriz, 15 - Centro',
    neighborhood: 'Centro',
    institution: 'sch-005',
    course: 'Ensino Médio - 2º Ano',
    shift: 'morning',
    schoolYear: 2025,
    plan: '5x',
    planPrice: 150.0,
    status: 'pending',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'pending',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-22T11:30:00Z',
    updatedAt: '2025-01-22T11:30:00Z',
    paymentStatus: 'pending',
    paymentDueDate: '2025-02-22',
    weeklyUsage: 0,
  },
  {
    id: 'stu-006',
    name: 'Rafael Almeida Lima',
    cpf: '67890123456',
    birthDate: '2004-09-12',
    phone: '31944332211',
    email: 'rafael.a@email.com',
    address: 'Rua das Acácias, 67 - Vila Santa Cruz',
    neighborhood: 'Vila Santa Cruz',
    institution: 'sch-002',
    course: 'Ensino Médio - 3º Ano',
    shift: 'morning',
    schoolYear: 2025,
    plan: '5x',
    planPrice: 150.0,
    status: 'rejected',
    rejectionReason: 'Declaração escolar fora do prazo de validade. Solicite uma nova declaração na secretaria da escola.',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-05T16:45:00Z',
    updatedAt: '2025-01-10T09:00:00Z',
    paymentStatus: 'pending',
    paymentDueDate: '2025-02-05',
    weeklyUsage: 0,
  },
  {
    id: 'stu-007',
    name: 'Juliana Martins Rocha',
    cpf: '78901234567',
    birthDate: '2005-12-01',
    phone: '31933221100',
    email: 'juliana.m@email.com',
    address: 'Rua dos Cravos, 210 - Bairro Novo',
    neighborhood: 'Bairro Novo',
    institution: 'sch-001',
    course: 'Ensino Médio - 1º Ano',
    shift: 'afternoon',
    schoolYear: 2025,
    plan: '1x',
    planPrice: 45.0,
    status: 'approved',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-14T13:00:00Z',
    updatedAt: '2025-01-19T10:30:00Z',
    paymentStatus: 'paid',
    paymentDueDate: '2025-02-14',
    cardId: 'CARD-2025-0004',
    weeklyUsage: 1,
  },
  {
    id: 'stu-008',
    name: 'Gabriel Santos Nascimento',
    cpf: '89012345678',
    birthDate: '2006-04-25',
    phone: '31922110099',
    email: 'gabriel.s@email.com',
    address: 'Avenida Central, 500 - Centro',
    neighborhood: 'Centro',
    institution: 'sch-003',
    course: 'Técnico em Eletrotécnica',
    shift: 'night',
    schoolYear: 2025,
    plan: '3x',
    planPrice: 95.0,
    status: 'correction',
    correctionReason: 'O comprovante de residência precisa estar em nome do responsável ou apresentar declaração de residência com firma reconhecida.',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-16T08:00:00Z',
    updatedAt: '2025-01-21T15:00:00Z',
    paymentStatus: 'pending',
    paymentDueDate: '2025-02-16',
    weeklyUsage: 0,
  },
  {
    id: 'stu-009',
    name: 'Larissa Beatriz Cunha',
    cpf: '90123456789',
    birthDate: '2005-08-14',
    phone: '31911009988',
    email: 'larissa.b@email.com',
    address: 'Rua das Margaridas, 33 - Jardim América',
    neighborhood: 'Jardim América',
    institution: 'sch-002',
    course: 'Ensino Médio - 3º Ano',
    shift: 'morning',
    schoolYear: 2025,
    plan: '5x',
    planPrice: 150.0,
    status: 'approved',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-03T10:30:00Z',
    updatedAt: '2025-01-08T12:00:00Z',
    paymentStatus: 'overdue',
    paymentDueDate: '2025-01-03',
    cardId: 'CARD-2025-0005',
    weeklyUsage: 4,
  },
  {
    id: 'stu-010',
    name: 'Thiago Rodrigues Pinto',
    cpf: '01234567890',
    birthDate: '2004-06-09',
    phone: '31900998877',
    email: 'thiago.r@email.com',
    address: 'Rua São José, 145 - Zona Sul',
    neighborhood: 'Zona Sul',
    institution: 'sch-004',
    course: 'Automação Industrial',
    shift: 'afternoon',
    schoolYear: 2025,
    plan: '5x',
    planPrice: 150.0,
    status: 'approved',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-07T15:45:00Z',
    updatedAt: '2025-01-12T09:30:00Z',
    paymentStatus: 'paid',
    paymentDueDate: '2025-02-07',
    cardId: 'CARD-2025-0006',
    weeklyUsage: 5,
  },
  {
    id: 'stu-011',
    name: 'Camila Fernandes Vieira',
    cpf: '11223344556',
    birthDate: '2005-02-28',
    phone: '31988664422',
    email: 'camila.f@email.com',
    address: 'Rua Boa Vista, 78 - Vila Santa Cruz',
    neighborhood: 'Vila Santa Cruz',
    institution: 'sch-005',
    course: 'Ensino Médio - 2º Ano',
    shift: 'morning',
    schoolYear: 2025,
    plan: '3x',
    planPrice: 95.0,
    status: 'pending',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'pending',
    },
    createdAt: '2025-01-23T09:00:00Z',
    updatedAt: '2025-01-23T09:00:00Z',
    paymentStatus: 'pending',
    paymentDueDate: '2025-02-23',
    weeklyUsage: 0,
  },
  {
    id: 'stu-012',
    name: 'Matheus Carvalho Dias',
    cpf: '22334455667',
    birthDate: '2006-10-17',
    phone: '31977553311',
    email: 'matheus.c@email.com',
    address: 'Rua da Paz, 190 - Bairro Novo',
    neighborhood: 'Bairro Novo',
    institution: 'sch-001',
    course: 'Ensino Médio - 1º Ano',
    shift: 'afternoon',
    schoolYear: 2025,
    plan: '5x',
    planPrice: 150.0,
    status: 'approved',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-09T11:15:00Z',
    updatedAt: '2025-01-14T14:30:00Z',
    paymentStatus: 'paid',
    paymentDueDate: '2025-02-09',
    cardId: 'CARD-2025-0007',
    weeklyUsage: 3,
  },
  {
    id: 'stu-013',
    name: 'Bianca Souza Mendes',
    cpf: '33445566778',
    birthDate: '2005-05-03',
    phone: '31966442200',
    email: 'bianca.s@email.com',
    address: 'Avenida Paulista, 230 - Centro',
    neighborhood: 'Centro',
    institution: 'sch-003',
    course: 'Técnico em Administração',
    shift: 'morning',
    schoolYear: 2025,
    plan: '3x',
    planPrice: 95.0,
    status: 'approved',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-11T07:45:00Z',
    updatedAt: '2025-01-16T10:00:00Z',
    paymentStatus: 'paid',
    paymentDueDate: '2025-02-11',
    cardId: 'CARD-2025-0008',
    weeklyUsage: 2,
  },
  {
    id: 'stu-014',
    name: 'Felipe Augusto Barbosa',
    cpf: '44556677889',
    birthDate: '2004-12-20',
    phone: '31955331199',
    email: 'felipe.a@email.com',
    address: 'Rua das Rosas, 56 - Distrito Industrial',
    neighborhood: 'Distrito Industrial',
    institution: 'sch-004',
    course: 'Técnico em Refrigeração',
    shift: 'night',
    schoolYear: 2025,
    plan: '3x',
    planPrice: 95.0,
    status: 'rejected',
    rejectionReason: 'O curso informado não consta na lista de cursos elegíveis para o transporte estudantil. Verifique com a coordenação.',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-13T12:30:00Z',
    updatedAt: '2025-01-18T08:15:00Z',
    paymentStatus: 'pending',
    paymentDueDate: '2025-02-13',
    weeklyUsage: 0,
  },
  {
    id: 'stu-015',
    name: 'Amanda Ribeiro Lopes',
    cpf: '55667788990',
    birthDate: '2006-07-08',
    phone: '31944220088',
    email: 'amanda.r@email.com',
    address: 'Rua Horizonte, 312 - Jardim América',
    neighborhood: 'Jardim América',
    institution: 'sch-002',
    course: 'Ensino Médio - 1º Ano',
    shift: 'morning',
    schoolYear: 2025,
    plan: '5x',
    planPrice: 150.0,
    status: 'correction',
    correctionReason: 'CPF informado diverge do documento anexado. Por favor, verifique os dados e envie novamente.',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-17T16:00:00Z',
    updatedAt: '2025-01-22T11:45:00Z',
    paymentStatus: 'pending',
    paymentDueDate: '2025-02-17',
    weeklyUsage: 0,
  },
  {
    id: 'stu-016',
    name: 'Davi Lucas Monteiro',
    cpf: '66778899001',
    birthDate: '2005-09-25',
    phone: '31933119977',
    email: 'davi.m@email.com',
    address: 'Rua Esperança, 89 - Vila Santa Cruz',
    neighborhood: 'Vila Santa Cruz',
    institution: 'sch-005',
    course: 'Ensino Médio - 3º Ano',
    shift: 'afternoon',
    schoolYear: 2025,
    plan: '1x',
    planPrice: 45.0,
    status: 'approved',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'uploaded',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-06T08:30:00Z',
    updatedAt: '2025-01-11T13:00:00Z',
    paymentStatus: 'paid',
    paymentDueDate: '2025-02-06',
    cardId: 'CARD-2025-0009',
    weeklyUsage: 1,
  },
  {
    id: 'stu-017',
    name: 'Letícia Oliveira Gomes',
    cpf: '77889900112',
    birthDate: '2006-03-11',
    phone: '31922008866',
    email: 'leticia.o@email.com',
    address: 'Rua Aurora, 167 - Zona Sul',
    neighborhood: 'Zona Sul',
    institution: 'sch-003',
    course: 'Técnico em Química',
    shift: 'morning',
    schoolYear: 2025,
    plan: '5x',
    planPrice: 150.0,
    status: 'pending',
    documents: {
      schoolDeclaration: 'uploaded',
      residenceProof: 'pending',
      personalDocument: 'uploaded',
    },
    createdAt: '2025-01-24T10:00:00Z',
    updatedAt: '2025-01-24T10:00:00Z',
    paymentStatus: 'pending',
    paymentDueDate: '2025-02-24',
    weeklyUsage: 0,
  },
]

// ── Boarding Records ──
export const boardingRecords: BoardingRecord[] = [
  {
    id: 'board-001',
    studentId: 'stu-001',
    studentName: 'Ana Clara Rodrigues',
    date: '2025-01-27',
    time: '06:45',
    route: 'route-001',
    driverName: 'Carlos Eduardo Silva',
    allowed: true,
  },
  {
    id: 'board-002',
    studentId: 'stu-002',
    studentName: 'Pedro Henrique Souza',
    date: '2025-01-27',
    time: '13:10',
    route: 'route-003',
    driverName: 'José Ferreira Lima',
    allowed: true,
  },
  {
    id: 'board-003',
    studentId: 'stu-003',
    studentName: 'Maria Eduarda Santos',
    date: '2025-01-27',
    time: '06:30',
    route: 'route-002',
    driverName: 'Roberto Almeida Santos',
    allowed: true,
  },
  {
    id: 'board-004',
    studentId: 'stu-004',
    studentName: 'Lucas Gabriel Oliveira',
    date: '2025-01-27',
    time: '13:00',
    route: 'route-004',
    driverName: 'Marcos Antônio Pereira',
    allowed: false,
    reason: 'Cadastro ainda pendente de aprovação pela secretaria',
  },
  {
    id: 'board-005',
    studentId: 'stu-007',
    studentName: 'Juliana Martins Rocha',
    date: '2025-01-27',
    time: '13:05',
    route: 'route-001',
    driverName: 'Carlos Eduardo Silva',
    allowed: true,
  },
  {
    id: 'board-006',
    studentId: 'stu-009',
    studentName: 'Larissa Beatriz Cunha',
    date: '2025-01-27',
    time: '06:50',
    route: 'route-003',
    driverName: 'José Ferreira Lima',
    allowed: true,
  },
  {
    id: 'board-007',
    studentId: 'stu-010',
    studentName: 'Thiago Rodrigues Pinto',
    date: '2025-01-27',
    time: '13:15',
    route: 'route-004',
    driverName: 'Marcos Antônio Pereira',
    allowed: true,
  },
  {
    id: 'board-008',
    studentId: 'stu-012',
    studentName: 'Matheus Carvalho Dias',
    date: '2025-01-27',
    time: '13:00',
    route: 'route-001',
    driverName: 'Carlos Eduardo Silva',
    allowed: true,
  },
  {
    id: 'board-009',
    studentId: 'stu-013',
    studentName: 'Bianca Souza Mendes',
    date: '2025-01-27',
    time: '06:40',
    route: 'route-002',
    driverName: 'Roberto Almeida Santos',
    allowed: true,
  },
  {
    id: 'board-010',
    studentId: 'stu-016',
    studentName: 'Davi Lucas Monteiro',
    date: '2025-01-27',
    time: '13:20',
    route: 'route-005',
    driverName: 'Fernando Costa Oliveira',
    allowed: true,
  },
  {
    id: 'board-011',
    studentId: 'stu-001',
    studentName: 'Ana Clara Rodrigues',
    date: '2025-01-28',
    time: '06:42',
    route: 'route-001',
    driverName: 'Carlos Eduardo Silva',
    allowed: true,
  },
  {
    id: 'board-012',
    studentId: 'stu-003',
    studentName: 'Maria Eduarda Santos',
    date: '2025-01-28',
    time: '06:28',
    route: 'route-002',
    driverName: 'Roberto Almeida Santos',
    allowed: true,
  },
]

// ── Notifications ──
export const notifications: Notification[] = [
  {
    id: 'notif-001',
    userId: 'admin',
    title: 'Novas solicitações cadastradas',
    message: '4 novas solicitações de transporte estão aguardando análise da secretaria.',
    type: 'info',
    read: false,
    createdAt: '2025-01-27T08:00:00Z',
  },
  {
    id: 'notif-002',
    userId: 'admin',
    title: 'Pagamento vencido',
    message: 'A aluna Larissa Beatriz Cunha possui pagamento vencido desde 03/01/2025.',
    type: 'warning',
    read: false,
    createdAt: '2025-01-27T09:00:00Z',
  },
  {
    id: 'notif-003',
    userId: 'admin',
    title: 'Cadastro aprovado',
    message: 'Ana Clara Rodrigues teve seu cadastro aprovado com sucesso.',
    type: 'success',
    read: true,
    createdAt: '2025-01-15T14:00:00Z',
  },
  {
    id: 'notif-004',
    userId: 'admin',
    title: 'Documento irregular',
    message: 'Gabriel Santos Nascimento foi colocado em correção - comprovante de residência irregular.',
    type: 'error',
    read: false,
    createdAt: '2025-01-21T15:00:00Z',
  },
  {
    id: 'notif-005',
    userId: 'admin',
    title: 'Embarque negado',
    message: 'Lucas Gabriel Oliveira tentou embarcar mas o cadastro ainda está pendente.',
    type: 'warning',
    read: true,
    createdAt: '2025-01-27T13:05:00Z',
  },
  {
    id: 'notif-006',
    userId: 'admin',
    title: 'Relatório mensal disponível',
    message: 'O relatório financeiro de janeiro de 2025 está pronto para visualização.',
    type: 'info',
    read: true,
    createdAt: '2025-01-28T08:00:00Z',
  },
  {
    id: 'notif-007',
    userId: 'admin',
    title: 'Novo cadastro rejeitado',
    message: 'Felipe Augusto Barbosa teve a solicitação rejeitada - curso não elegível.',
    type: 'error',
    read: false,
    createdAt: '2025-01-18T08:15:00Z',
  },
]

// ── Dashboard Stats ──
export const dashboardStats: DashboardStats = {
  totalStudents: 17,
  approvedStudents: 9,
  pendingStudents: 4,
  monthlyRevenue: 1175.0,
  activeBoardingsToday: 12,
  routesActive: 5,
}

// ── Chart data: Students by Status ──
export const studentsByStatus: ChartData[] = [
  { name: 'Aprovados', value: 9 },
  { name: 'Pendentes', value: 4 },
  { name: 'Rejeitados', value: 2 },
  { name: 'Correção', value: 2 },
]

// ── Chart data: Revenue by month ──
export const revenueByMonth: ChartData[] = [
  { name: 'Set', value: 980 },
  { name: 'Out', value: 1250 },
  { name: 'Nov', value: 1100 },
  { name: 'Dez', value: 1350 },
  { name: 'Jan', value: 1175 },
]

// ── Chart data: Boardings per route ──
export const boardingsPerRoute: ChartData[] = [
  { name: 'Linha 01', value: 35 },
  { name: 'Linha 02', value: 28 },
  { name: 'Linha 03', value: 22 },
  { name: 'Linha 04', value: 18 },
  { name: 'Linha 05', value: 15 },
]

// ── Chart data: Plans distribution ──
export const plansDistribution: ChartData[] = [
  { name: '1x por semana', value: 2 },
  { name: '3x por semana', value: 6 },
  { name: '5x por semana', value: 9 },
]

// ── Current user (mock) ──
export const currentUser: User = {
  id: 'user-001',
  name: 'Administração Municipal',
  role: 'admin',
  email: 'admin@sicontrola.gov.br',
}
